export const createUserWithEmailAndPassword = jest.fn((auth, email, password) => Promise.reject({ code: 'auth/invalid-email' }));
Promise.reject();
Promise.resolve({});
export const signInWithEmailAndPassword = () => Promise.resolve({});
export const GoogleAuthProvider = () => Promise.resolve({});
export const signInWithPopup = () => Promise.resolve({});
export const onAuthStateChanged = () => Promise.resolve({});
export const signOut = () => Promise.resolve({});
export const db = () => Promise.resolve({});
export const collection = () => Promise.resolve({});
export const addDoc = () => Promise.resolve({});
export const getDocs = () => Promise.resolve({});
export const getDoc = () => Promise.resolve({});
export const onSnapshot = () => Promise.resolve({});
export const doc = () => Promise.resolve({});
export const query = () => Promise.resolve({});
export const updateDoc = () => Promise.resolve({});
export const serverTimestamp = () => Promise.resolve({});
export const orderBy = () => Promise.resolve({});
export const deleteDoc = () => Promise.resolve({});
export const provider = () => Promise.resolve({});
export const arrayUnion = () => Promise.resolve({});
export const arrayRemove = () => Promise.resolve({});
